name: widget-server pipe DockerHub

on:
  push:
    branches: ['main']

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest # Essa máquina já tem o Docker instalado
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4 # Add-on to checkout to branch
            
#       - name: Login to DockerHub
#         id: login-docker-hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME}}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}


#       - name: Generate tag # Queremos pegar a hash do commit e criamos a variavel sha para a saída de uma execução
#         id: generate_tag
#         run: |
#           SHA=$(echo $GITHUB_SHA | head -c7) 
#           echo "sha=$SHA" >> $GITHUB_OUTPUT

#       - name: Build and push the image to DockerHub
#         id: build-push-image
#         env:
#             DOCKERHUB_REPOSITORY: ${{ vars.DOCKERHUB_REPOSITORY }}
#             IMAGE_TAG: ${{ steps.generate_tag.outputs.sha }}
#         run: | # precisamos dessa pipe para rodar múltiplos comandos inline
#           docker build -t $DOCKERHUB_REPOSITORY:$IMAGE_TAG .
#           docker push $DOCKERHUB_REPOSITORY:$IMAGE_TAG
