name: widget-server pipe ECR

on:
  push:
    branches: ['main']

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest # Essa máquina já tem o Docker instalado
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4 # Add-on to checkout to branch
            
      - name: Configure AWS credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr # Identificador do step, pode ajudar caso esse step dependa de algo já executado
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate tag # Queremos pegar a hash do commit e criamos a variavel sha para a saída de uma execução
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7) 
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build and push the image to AWS ECR
        id: build-push-image
        env:
            ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }} # Nós precisamos indicar o ID do step para conseguir pegar o output
            IMAGE_TAG: ${{ steps.generate_tag.outputs.sha }}
        run: | # precisamos dessa pipe para rodar múltiplos comandos inline
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
