name: widget-server pipe

on:
  push:
    branches: ['main']
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest # Essa máquina já tem o Docker instalado
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4 # Add-on to checkout to branch
            
      - name: Configure AWS credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr # Identificador do step, pode ajudar caso esse step dependa de algo já executado
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push the image to AWS ECR
        id: build-push-image
        run: | # precisamos dessa pipe para rodar múltiplos comandos inline
          docker build -t widget-server:v3 .
          docker tag widget-server:v3 286549082806.dkr.ecr.us-east-2.amazonaws.com/rocketseat/widget-server:v3
          docker push 286549082806.dkr.ecr.us-east-2.amazonaws.com/rocketseat/widget-server:v3
